### ISSUE TITLE
Use bilinear interpolation for rasters

### ISSUE THREAD

**Issue by dnomadb** [mapbox/tilelive-vector#114]
Currently we are using nearest neighbor (the mapnik default) interpolation for the raster symbolizer:
https://github.com/mapbox/tilelive-vector/blob/master/templates/layer.xml#L21

Changing it to `scaling="bilinear"` will give better looking output tiles, which is especially important if we move towards resolution rounding as detailed here: https://github.com/mapbox/mapnik-omnivore/issues/133

cc @yhahn @springmeyer @perrygeo

**Comment by springmeyer** [comment]
:+1: 

 Also, while you are at it can you remove the `<ElseFilter></ElseFilter>` line. That is junk and not doing anything helpful. Just drop this: https://github.com/mapbox/tilelive-vector/blob/master/templates/layer.xml#L20

**Comment by perrygeo** [comment]
@yhahn brought up the fact that this might have some negative impact on performance. Has anyone done the benchmarks to see how much impact bilinear vs nearest has?

Clarifying question: is this RasterSymbolizer only put to use for overzoomed rasters?

**Comment by springmeyer** [comment]
Yes, bilinear scaling is more expensive than nearest as we have an optimized path in Mapnik for nearest: https://github.com/mapnik/mapnik/blob/master/src/image_scaling.cpp#L148-L166. So it is worth benchmarking. However I would not be surprised if benchmarking would not pick up a measurable difference.

> Clarifying question: is this RasterSymbolizer only put to use for overzoomed rasters?

Best answered by @yhahn. Another question to keep in mind is "What is the impact when raster layers are composited serverside into a new vector tile with other layers". In this case we default to bilinear scaling: https://github.com/mapnik/node-mapnik/blob/master/src/mapnik_vector_tile.cpp#L922

**Comment by celoyd** [comment]
:+1: for bilinear on aesthetics grounds. The perceived quality is considerably higher. People don’t get as mad at blur as they get at pixely-ness.

**Comment by perrygeo** [comment]
Based on @yhahn's `test-fillzoom` branch, I was able to test bilinear resampling in overzooms:

* bilinear makes the images less blocky, more blurry as expected
* It does *not* make any difference in terms of spatial alignment.

Here's the results for the current default
![xray-fillzoom-2-1-1 original](https://cloud.githubusercontent.com/assets/1151287/12271339/d74fb9b2-b930-11e5-8a22-d9afa55fb772.jpg)
and for bilinear
![xray-fillzoom-2-1-1](https://cloud.githubusercontent.com/assets/1151287/12271343/dd522796-b930-11e5-9f07-9770095b5aea.jpg)
and together in a gif (no shift here)
![xray](https://cloud.githubusercontent.com/assets/1151287/12271382/1040af9c-b931-11e5-8c1d-ea9385e36794.gif)

Here's the diff in case we decide to apply this (in `map.xml`, not `layer.xml` as written above)
```
diff --git a/templates/map.xml b/templates/map.xml
index 1158f3d..4ebc9e6 100644
--- a/templates/map.xml
+++ b/templates/map.xml
@@ -15,7 +15,7 @@

 <Style name="_image" filter-mode="first">
   <Rule>
-    <RasterSymbolizer opacity="1" />
+    <RasterSymbolizer opacity="1" scaling="bilinear" />
   </Rule>
 </Style>
```

**Comment by sgillies** [comment]
@dnomadb this smells like it's related what's going on in https://github.com/mapbox/unpacker/issues/752: pixelated overview tiles.

**Comment by dnomadb** [comment]
I am going to test this out for performance + quality increase. Here are what I see are the steps:

- [ ] Branch off and integrate bilinear resampling here
- [ ] Integrate this into a branch of [`mapbox-maps`](https://github.com/mapbox/mapbox-maps/blob/master/package.json#L36)
- [ ] Publish this `mapbox-maps` branch as a `-dev` release
- [ ] Bring this release into a branch of [`api-maps`](https://github.com/mapbox/api-maps)
- [ ] Deploy this `api-maps` branch to staging
- [ ] Benchmark this via [`bench`](https://github.com/mapbox/bench)
- [ ] Inspect visual quality and weigh against results of ^ to decide whether this is :+1: / :-1: 

I'll update this hitlist as I find all the parts I missed :D

**Comment by perrygeo** [comment]
Some node version problems with tilelive-vector tests: https://travis-ci.org/mapbox/tilelive-vector/builds/109968314

**Comment by springmeyer** [comment]
@perrygeo I've also seen those and they are a mystery still (https://github.com/mapbox/tilelive-vector/pull/119). They are therefore very unlikely related to your work and rather a problem we currently have in master.

**Comment by perrygeo** [comment]
Thanks @springmeyer - I'll ignore it for now.

I'm currently testing `api-maps` locally and hitting a seemingly unrelated failure: https://gist.github.com/perrygeo/ab4ddd9e7e54d68da33b

@dnomadb  Whaddya think? Move on and try it on staging regardless.

**Comment by dnomadb** [comment]
>  Move on and try it on staging regardless.

@perrygeo :+1:

**Comment by perrygeo** [comment]
So trying out [these instructions](https://github.com/mapbox/api-maps#stage-a-staging-stack) to launch a staging stack for `api-maps@bilinear` I'm getting this error from the logs

```
[Thu, 18 Feb 2016 17:39:03 GMT] [info] [http] "GET / HTTP/1.1" 500 35 "-" "ELB-HealthChecker/1.0" "-" 24.810 ms
[Thu, 18 Feb 2016 17:39:08 GMT] [error] [default] ResourceNotFoundException: Requested resource not found
    at Request.extractError (/usr/local/src/app/node_modules/mapbox-core/node_modules/dyno/node_modules/aws-sdk/lib/protocol/json.js:43:27)
    at Request.callListeners (/usr/local/src/app/node_modules/mapbox-core/node_modules/dyno/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at Request.emit (/usr/local/src/app/node_modules/mapbox-core/node_modules/dyno/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/src/app/node_modules/mapbox-core/node_modules/dyno/node_modules/aws-sdk/lib/request.js:604:14)
    at Request.transition (/usr/local/src/app/node_modules/mapbox-core/node_modules/dyno/node_modules/aws-sdk/lib/request.js:21:12)
    at AcceptorStateMachine.runTo (/usr/local/src/app/node_modules/mapbox-core/node_modules/dyno/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/src/app/node_modules/mapbox-core/node_modules/dyno/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/src/app/node_modules/mapbox-core/node_modules/dyno/node_modules/aws-sdk/lib/request.js:22:9)
    at Request.<anonymous> (/usr/local/src/app/node_modules/mapbox-core/node_modules/dyno/node_modules/aws-sdk/lib/request.js:606:12)
    at Request.callListeners (/usr/local/src/app/node_modules/mapbox-core/node_modules/dyno/node_modules/aws-sdk/lib/sequential_executor.js:104:18)
    message: Requested resource not found
    code: ResourceNotFoundException
    statusCode: 400
    retryDelay: 0
    status: 500
    url: /
    method: GET
```

And here's the [full log](https://gist.githubusercontent.com/perrygeo/dbc9b1fbab33d6990d02/raw/f3d77069f5bc1fc3eae2be84524a41be34384128/api-maps%2520staging%2520error%2520log.txt). I haven't dug into reasons why, just deleted the stack until I have more bandwidth to dig in.

**Comment by perrygeo** [comment]
Picking this up again, now I'm getting errors on `mbx create`

```
$ mbx create bilinear
You are deploying branch 'bilinear' instead of 'master'. Are you sure? [Y/n] y
16:17:58Z us-east-1: creating stack api-maps-bilinear

/Users/mperry/work/mbxcli/node_modules/aws-sdk/lib/request.js:30
            throw err;
                  ^
Error: Cannot find module 'vpc-cfn'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/mperry/work/api-maps/cloudformation/api-maps.template.js:2:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I'm `mbx auth`'d, I pulled, npm installed and linked the latest `mbxcli` and still getting this error.

**Comment by perrygeo** [comment]
Tested on api-maps@bilinear - no bueno. Trying round 2 by adding bilinear to `templates.layer.xml` as well as `map.xml`

**Comment by perrygeo** [comment]
Alright, so all the tests are broken and I'm confused about the distinction between layer.xml and map.xml but we've got some preliminary results

Looking at the mapbox.satellite [tilejson](http://api-maps-bilinear-vpc-632541875.us-east-1.elb.amazonaws.com/v4/mapbox.satellite.json?access_token=pk.eyJ1IjoicGVycnlnZW8iLCJhIjoiY2lsOGd3dGRxMDAwYXN6bTBxemhnNm5lcyJ9.OJbdkgZOGRPRJZ0RZUpPCw) we see a `maxzoom: 19`

So a standard 256 [z19 tile](https://a.tiles.mapbox.com/v4/mapbox.satellite/19/105042/203882.png?access_token=pk.eyJ1IjoiZG5vbWFkYiIsImEiOiJEak5aTXdZIn0.UtQIRl-MzHHZk6TIAHSWww) should be the same, no overzoom. :heavy_check_mark:  while the 2x versions should differ. :heavy_check_mark: 
```
$ diff 203882_1x_bilinear.png 203882_1x_default.png
$ diff 203882_2x_bilinear.png 203882_2x_default.png
Binary files 203882_2x_bilinear.png and 203882_2x_default.png differ
```

The difference is due to the bilinear interpolation. **The current default**

![203882_2x_default](https://cloud.githubusercontent.com/assets/1151287/13431739/ff9e1846-dfa0-11e5-8172-7564b705892f.png)

**With bilinear**

![203882_1x_bilinear](https://cloud.githubusercontent.com/assets/1151287/13431753/09c43418-dfa1-11e5-8e4e-1d64d7f77c6f.png)

**Comment by perrygeo** [comment]
In terms of benchmarking for speed, I'm not sure `bench` is going to be very helpful as it's more likely to pick up differences in infrastructure than in the actual tile generation process. We need to reduce extraneous variables, not add them.

Still, bench makes it easy enough to run them so I started two stacks and ran bench:
* `api-maps@master`: [results](https://hey.mapbox.com/bench/2016-03-01-1456855799.html) show 2154.8 requests/s
* `api-maps@bilinear`: [results](https://hey.mapbox.com/bench/2016-03-01-1456854683.html) show 4052.4/s

Does this say that bilinear is twice as fast? No, more likely that the difference in network traffic or some other external variable.

Here's the invocations:
```
mbx watchbot queue '{"urls":["http://api-maps-bilinear-VPC-632541875.us-east-1.elb.amazonaws.com/v4/mapbox.satellite/{z}/{x}/{y}.png"]}' production
mbx watchbot queue '{"urls":["http://api-maps-notbilinear-VPC-1856557177.us-east-1.elb.amazonaws.com/v4/mapbox.satellite/{z}/{x}/{y}.png"]}' production
```

**Comment by yhahn** [comment]
Per chat, ^^ the benchmarks above are benching the endpoint when it returns a 401 unauthorized response. Try rerunning the benchmarks with `?access_token=<token>` in the URL and maybe check a `0/0/0` tile before running the bench as well to make sure the stack will serve images for the URLs in question.

**Comment by perrygeo** [comment]
Thanks @yhahn @dnomadb - updated results ^^^ - pretty close results. I'm gonna try with 2x z19 tiles only next.

**Comment by perrygeo** [comment]
Forcing z19 2x pngs

* [default/master](https://hey.mapbox.com/bench/2016-03-01-1456859797.html) = 78.8/s
* [bilinear](https://hey.mapbox.com/bench/2016-03-01-1456859716.html) = 74.4/s


```
mbx watchbot queue '{"minzoom":19,"urls":["http://api-maps-bilinear-VPC-632541875.us-east-1.elb.amazonaws.com/v4/mapbox.satellite/{z}/{x}/{y}@2x.png?access_token=pk.eyJ1IjoicGVycnlnZW8iLCJhIjoiY2lsOGd3dGRxMDAwYXN6bTBxemhnNm5lcyJ9.OJbdkgZOGRPRJZ0RZUpPCw"]}' production
mbx watchbot queue '{"minzoom":19,"urls":["http://api-maps-notbilinear-VPC-1856557177.us-east-1.elb.amazonaws.com/v4/mapbox.satellite/{z}/{x}/{y}@2x.png?access_token=pk.eyJ1IjoicGVycnlnZW8iLCJhIjoiY2lsOGd3dGRxMDAwYXN6bTBxemhnNm5lcyJ9.OJbdkgZOGRPRJZ0RZUpPCw"]}' production
```

So, discounting extraneous variables, it looks like **bilinear adds about 5% to the response time**. Not horrible. We could go deeper to try to really isolate the rendering times sans network but let's stick with that rough assumption for now.

**Comment by camillacaros** [comment]
Liking what we're seeing so far with bilinear! Smoother edges on buildings, and an easing of the columning effect in color elsewhere.

*Default on left // Bilinear on right:*
![screen shot 2016-03-01 at 11 42 11 am](https://cloud.githubusercontent.com/assets/3768909/13439495/b5330a6c-dfa2-11e5-8929-4fddb8968095.png)

**Comment by perrygeo** [comment]
> like buttah

Y, I think it's an improvement and it certainly smooths out a lot of the artifacts of compression and overzooming. 

The :moneybag: question: Is the visual improvement big enough to justify moving forward?

Pros:
* less grainy, more smoothy
* less noticable artifacts

Cons:
* the lift to merge, update test suites, cut releases and deploy.
* the slight 5% performance hit
* only impacts imagery that is actually overzoomed (IOW zero difference for `mapbox.satellite` at 256px z19 tiles)
* a bit of an unknown how/if this will affect other renders like user-uploaded rasters and other tilesets (this is mostly reflecting my own ignorance of the system)
