### ISSUE TITLE
npm install with node v8.5.0 fails

### ISSUE THREAD

**Issue by apavani** [mapbox/tilelive-vector#146]
Looks like this is an issue with the node-pre-gyp installation during the mapnik dependency install
> mapnik@3.5.14 install F:\Projects\Maps\Leaflet\node_modules\tilelive-vector\node_modules\mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.5.14/Release/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.5.14 and node@8.5.0 (node-v57 ABI) (falling back to source compile with node-gyp)

F:\Projects\Maps\Leaflet\node_modules\tilelive-vector\node_modules\mapnik>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

F:\Projects\Maps\Leaflet\node_modules\tilelive-vector\node_modules\mapnik>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=F:\Projects\Maps\Leaflet\node_modules\tilelive-vector\node_modules\mapnik\lib\binding\node-v57-win32-x64\mapnik.node --module_name=mapnik --module_path=F:\Projects\Maps\Leaflet\node_modules\tilelive-vector\node_modules\mapnik\lib\binding\node-v57-win32-x64 )  else (node "" configure --fallback-to-build --module=F:\Projects\Maps\Leaflet\node_modules\tilelive-vector\node_modules\mapnik\lib\binding\node-v57-win32-x64\mapnik.node --module_name=mapnik --module_path=F:\Projects\Maps\Leaflet\node_modules\tilelive-vector\node_modules\mapnik\lib\binding\node-v57-win32-x64 )
'mapnik-config' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to 'mapnik-config --ldflags' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=F:\\Projects\\Maps\\Leaflet\\node_modules\\tilelive-vector\\node_modules\\mapnik\\lib\\binding\\node-v57-win32-x64\\mapnik.node" "--module_name=mapnik" "--module_path=F:\\Projects\\Maps\\Leaflet\\node_modules\\tilelive-vector\\node_modules\\mapnik\\lib\\binding\\node-v57-win32-x64"
gyp ERR! cwd F:\Projects\Maps\Leaflet\node_modules\tilelive-vector\node_modules\mapnik
gyp ERR! node -v v8.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=F:\Projects\Maps\Leaflet\node_modules\tilelive-vector\node_modules\mapnik\lib\binding\node-v57-win32-x64\mapnik.node --module_name=mapnik --module_path=F:\Projects\Maps\Leaflet\node_modules\tilelive-vector\node_modules\mapnik\lib\binding\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (F:\Projects\Maps\Leaflet\node_modules\tilelive-vector\node_modules\mapnik\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\Projects\\Maps\\Leaflet\\node_modules\\tilelive-vector\\node_modules\\mapnik\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd F:\Projects\Maps\Leaflet\node_modules\tilelive-vector\node_modules\mapnik
node-pre-gyp ERR! node -v v8.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=F:\Projects\Maps\Leaflet\node_modules\tilelive-vector\node_modules\mapnik\lib\binding\node-v57-win32-x64\mapnik.node --module_name=mapnik --module_path=F:\Projects\Maps\Leaflet\node_modules\tilelive-vector\node_modules\mapnik\lib\binding\node-v57-win32-x64' (1)
npm WARN mpo@1.0.0 No repository field.
npm WARN mpo@1.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mapnik@3.5.14 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapnik@3.5.14 install script.

**Comment by apavani** [comment]
I tried npm install tilelive-vector with node v5.7.0, v5.7.1 as well as v6.11.3
I got the same result even there..

**Comment by remmi11** [comment]
Did you find resolution here?  I am experiencing this also and with only tilelive-vector. 
Node 8.9.4
NPM 5.6.0
